### ISSUE TITLE
I really want to use your work

### ISSUE THREAD

**Issue by rmcpl4ay** [kanewi11/telegram-reaction-bot#1]
Do you have an explainer video for a layman?

**Comment by kanewi11** [comment]
> 

Hi. It's very easy to use, I've practically written everything in the README.md. What exactly is not working?

**Comment by rmcpl4ay** [comment]
I downloaded python, I try to open config.py and it immediately closes..
Do you have discord?

**Comment by kanewi11** [comment]
> I downloaded python, I try to open config.py and it immediately closes..
> Do you have discord?

@rmcpl4ay Give me u discord

**Comment by rmcpl4ay** [comment]
> JackkMATADOR#0102
