### ISSUE TITLE
Phone number Ban

### ISSUE THREAD

**Issue by Frido-Cpp** [kanewi11/telegram-reaction-bot#2]
Please do you have any Idea why telegram bans phone numbers few minutes after login with telethon?, It wasn't like 1month back

**Comment by kanewi11** [comment]
Most likely you need to pass additional arguments in the parameters, such as application version, etc.

Although maybe you have a lot of requests of the same type and Telegram considers them as inhuman behavior.

**Comment by Frido-Cpp** [comment]
Bro, I used telethon on  a new pc, and login a new account, and few minutes after, the account was banned without me making any request or flooding. Please how can I pass those parameters?

**Comment by kanewi11** [comment]
https://docs.telethon.dev/en/stable/modules/client.html

```
telethon.client.telegramclient.TelegramClient(session: typing.Union[str, Session], api_id: int, api_hash: str, *, connection: typing.Type[Connection] = <class 'telethon.network.connection.tcpfull.ConnectionTcpFull'>, use_ipv6: bool = False, proxy: Union[tuple, dict] = None, local_addr: Union[str, tuple] = None, timeout: int = 10, request_retries: int = 5, connection_retries: int = 5, retry_delay: int = 1, auto_reconnect: bool = True, sequential_updates: bool = False, flood_sleep_threshold: int = 60, raise_last_call_error: bool = False, device_model: str = None, system_version: str = None, app_version: str = None, lang_code: str = 'en', system_lang_code: str = 'en', loop: asyncio.events.AbstractEventLoop = None, base_logger: Union[str, logging.Logger] = None, receive_updates: bool = True, catch_up: bool = False)
```

**Comment by Frido-Cpp** [comment]
Thanks man..
