### ISSUE TITLE
uvloop exception fix

### ISSUE THREAD

**Issue by Junior00369** [kanewi11/telegram-reaction-bot#4]
Traceback (most recent call last):
  File "reactionbot.py", line 12, in <module>
    import uvloop
ModuleNotFoundError: No module named 'uvloop'
How can I fix it?
![Captura de tela 2023-04-25 033500](https://user-images.githubusercontent.com/131751016/234206657-f486dba2-880a-4dcd-9197-4470e9f5bfc8.png)

**Comment by kanewi11** [comment]
_pip install uvloop_

**Comment by kanewi11** [comment]
If you are on Windows, before I rewrite the program, wait. Or remove the line with `uvloop==0.17.0` from `requirements.txt` and also in `reactionbot.py` on line 12 `import uvloop` and `uvloop.install()` on line 314
